CoreDepartment/Models/Context.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDepartment.Models
{
    public class Context : DbContext
    {

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {

            optionsBuilder.UseSqlServer("server=LAPTOP-G0H4BO0U\\SQLEXPRESS2017; " +
                "database=coreemployees; integrated security = true;");

        }


        public DbSet<Department> departments { get; set; }
        public DbSet<Employee> employees { get; set; }
    }
}

CoreDepartment/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDepartment.Models
{
    public class Department
    {
        [Key]
        public int ID { get; set; }
        public string DepartmentName { get; set; }

        public List<Employee> Employees { get; set; }


    }
}

CoreDepartment/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDepartment.Models
{
    public class Employee
    {
        [Key]
        public int ID { get; set; }
        public string EmpName { get; set; }
        public string EmpLastname { get; set; }
        public string EmpCity { get; set; }

        public Department depart { get; set; }
    }
}

CoreDepartment/Models/ErrorViewModel.cs
using System;

namespace CoreDepartment.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoreDepartment/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoreDepartment.Models;

namespace CoreDepartment.Controllers
{
    public class DepartmentsController : Controller
    {

        Context c = new Context();

        public IActionResult Index()
        {
            var depts = c.departments.ToList();
            return View(depts);
        }

        [HttpGet]
        public IActionResult NewDepartment()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewDepartment(Department d)
        {
            c.departments.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult DeleteDepartment(int id)
        {

            var dep = c.departments.Find(id);
            c.departments.Remove(dep);
            c.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult GetDepartment(int id)
        {
            var dep = c.departments.Find(id);

            return View("GetDepartment", dep);
        }

        public IActionResult UpdateDepartment(Department d)
        {
            var dep = c.departments.Find(d.ID);
            dep.DepartmentName = d.DepartmentName;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CoreDepartment/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreDepartment.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CoreDepartment.Controllers
{
    public class EmployeesController : Controller
    {

        Context c = new Context();

        public IActionResult Index()
        {
            var list = c.employees.Include(x => x.depart).ToList();
            return View(list);
        }

        [HttpGet]
        public IActionResult NewEmployee()
        {

            List<SelectListItem> departs = (from x in c.departments.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.DepartmentName,
                                                Value = x.ID.ToString()

                                            }).ToList();

            ViewBag.departList = departs;
            
            return View();
        }

        [HttpPost]
        public IActionResult NewEmployee(Employee e)
        {
            var dep = c.departments.Where(x => x.ID == e.depart.ID).FirstOrDefault();
            e.depart = dep;
            c.employees.Add(e);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult DeleteEmployee(int id)
        {

            var dep = c.employees.Find(id);
            c.employees.Remove(dep);
            c.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult GetEmployee(int id)
        {
            var emp = c.employees.Find(id);


            List<SelectListItem> departs = (from x in c.departments.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.DepartmentName,
                                                Value = x.ID.ToString()

                                            }).ToList();

            ViewBag.departList = departs;


            return View("GetEmployee", emp);
        }

        public IActionResult UpdateEmployee(Employee e)
        {
            var emp = c.employees.Find(e.ID);
            emp.EmpName = e.EmpName;
            emp.EmpLastname = e.EmpLastname;
            emp.EmpCity = e.EmpCity;

            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CoreDepartment/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoreDepartment.Models;

namespace CoreDepartment.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CoreDepartment/Views/Departments/GetDepartment.cshtml
@model CoreDepartment.Models.Department
@{
    ViewData["Title"] = "GetDepartment";
    Layout = "~/Views/Shared/_Sidebar.cshtml";
}

@using (Html.BeginForm("UpdateDepartment", "Departments", FormMethod.Post))
{

    <br />

    @Html.LabelFor(x => x.ID)
    @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })

    <br />

    @Html.LabelFor(x => x.DepartmentName)
    @Html.TextBoxFor(x => x.DepartmentName, new { @class = "form-control" })

    <br />  
    <button class="btn btn-info">Update</button>
}

CoreDepartment/Views/Departments/Index.cshtml
@model List<CoreDepartment.Models.Department>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Sidebar.cshtml";
}

<br />

<table class="table table-bordered">

    <tr class="bg-info">
        <th>ID</th>
        <th>Department</th>
        <th>Delete</th>
        <th>Update</th>

    </tr>

    @foreach(var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.DepartmentName</td>
            <td><a href="/Departments/DeleteDepartment/@x.ID" class="btn btn-danger">Delete</a></td>
            <td><a href="/Departments/GetDepartment/@x.ID" class="btn btn-success">Update</a></td>



        </tr>
    }

</table>
<a href="/Departments/NewDepartment/" class="btn btn-primary">Add New Department</a>

CoreDepartment/Views/Departments/NewDepartment.cshtml
@model CoreDepartment.Models.Department
@{
    ViewData["Title"] = "NewDepartment";
    Layout = "~/Views/Shared/_Sidebar.cshtml";
}

<br />
<form class="form-group" method="post">

    @Html.LabelFor(x => x.DepartmentName)
    @Html.TextBoxFor(x => x.DepartmentName, new { @class="form-control" })
    
    <br/>
    <button class="btn btn-info">Add</button>

</form>

CoreDepartment/Views/Employees/GetEmployee.cshtml
@model CoreDepartment.Models.Employee
@{
    ViewData["Title"] = "GetDepartment";
    Layout = "~/Views/Shared/_Sidebar.cshtml";
}

@using (Html.BeginForm("UpdateEmployee", "Employees", FormMethod.Post))
{

    <br />

    @Html.LabelFor(x => x.ID)
    @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })

    <br />

    @Html.LabelFor(x => x.EmpName)
    @Html.TextBoxFor(x => x.EmpName, new { @class = "form-control" })


    <br />

    @Html.LabelFor(x => x.EmpLastname)
    @Html.TextBoxFor(x => x.EmpLastname, new { @class = "form-control" })


    <br />

    @Html.LabelFor(x => x.EmpCity)
    @Html.TextBoxFor(x => x.EmpCity, new { @class = "form-control" })


    <br />
    <button class="btn btn-info">Update</button>
}

CoreDepartment/Views/Employees/Index.cshtml
@model List<CoreDepartment.Models.Employee>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Sidebar.cshtml";
}

<br />

<table class="table table-bordered">

    <tr class="bg-info">
        <th>ID</th>
        <th>Name</th>
        <th>City</th>
        <th>Department</th>
        <th>Delete</th>
        <th>Update</th>

    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.EmpName @x.EmpLastname</td>
            <td>@x.EmpCity</td>
            <td>@x.depart.DepartmentName</td>
            <td><a href="/Employees/DeleteEmployee/@x.ID" class="btn btn-danger">Delete</a></td>
            <td><a href="/Employees/GetEmployee/@x.ID" class="btn btn-success">Update</a></td>



        </tr>
    }

</table>
<a href="/Employees/NewEmployee/" class="btn btn-primary">Add New Employee</a>

CoreDepartment/Views/Employees/NewEmployee.cshtml
@model CoreDepartment.Models.Employee
@{
    ViewData["Title"] = "NewDepartment";
    Layout = "~/Views/Shared/_Sidebar.cshtml";
}

<br />
<form class="form-group" method="post">

    @Html.LabelFor(x => x.EmpName)
    @Html.TextBoxFor(x => x.EmpName, new { @class = "form-control" })

    @Html.LabelFor(x => x.EmpLastname)
    @Html.TextBoxFor(x => x.EmpLastname, new { @class = "form-control" })

    @Html.LabelFor(x => x.EmpCity)
    @Html.TextBoxFor(x => x.EmpCity, new { @class = "form-control" })

    @Html.LabelFor(x => x.depart)
    @Html.DropDownListFor(x => x.depart.ID, (List<SelectListItem>) ViewBag.departList, new { @class = "form-control" })

    <br />
    <button class="btn btn-info">Add</button>

</form>

CoreDepartment/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CoreDepartment/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CoreDepartment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

CoreDepartment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreDepartment</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CoreDepartment</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - CoreDepartment</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CoreDepartment/Views/Shared/_Sidebar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menu</h3>
        <a href="/Departments/Index/" class="w3-bar-item w3-button">Departments</a>
        <a href="/Employees/Index/" class="w3-bar-item w3-button">Employees</a>
        <a href="#" class="w3-bar-item w3-button">About Us</a>
        <a href="#" class="w3-bar-item w3-button">Exit</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-indigo">
            <h1>.NET Core App</h1>
        </div>



        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

</body>
</html>